### ISSUE TITLE
Doesn't work with deno-postgres

### ISSUE THREAD

**Issue by kt3k** [lucacasonato/now-deno#17]
I'm trying to use deno-postgres with now-deno as [this example](https://github.com/kt3k/now-deno-example/blob/master/api/read.ts). But this doesn't deploy to now with the following build time error.

```
...
2020-02-13T16:22:18.209Z  Download https://deno.land/x/checksum@1.0.1/md5.ts
2020-02-13T16:22:18.209Z  Download https://deno.land/x/postgres/encode.ts
2020-02-13T16:22:18.209Z  Download https://deno.land/x/postgres/decode.ts
2020-02-13T16:22:18.209Z  Download https://deno.land/x/postgres/oid.ts
2020-02-13T16:22:18.209Z  Download https://deno.land/x/postgres/deferred.ts
2020-02-13T16:22:18.209Z  
2020-02-13T16:22:18.209Z  error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'esnext' or 'system'.
2020-02-13T16:22:18.210Z  
2020-02-13T16:22:18.210Z  ► https://deno.land/std@v0.31.0/testing/runner.ts:294:5
2020-02-13T16:22:18.210Z  
2020-02-13T16:22:18.210Z  294 if (import.meta.main) {
2020-02-13T16:22:18.210Z          ~~~~~~~~~~~
2020-02-13T16:22:18.210Z  
2020-02-13T16:22:18.210Z  
2020-02-13T16:22:18.210Z      at buildDenoLambda (/zeit/82db6065a0e33879/.build-utils/.builder/node_modules/now-deno/dist/index.js:63:15)
2020-02-13T16:22:18.210Z      at runMicrotasks (<anonymous>)
2020-02-13T16:22:18.210Z      at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-02-13T16:22:18.270Z  worker exited with code 20 and signal null
2020-02-13T16:22:20.560Z  Done with "api/read.ts"
```

**Comment by kt3k** [comment]
This issue looks the same as https://github.com/denoland/deno/issues/2553, and the issue is already resolved at master of deno very recently. This must be fixed with the next release of deno.

Closing as it's not an issue of this repository.
