### ISSUE TITLE
Issues Bundling

### ISSUE THREAD

**Issue by khrome83** [lucacasonato/now-deno#28]
Is there anything that prevents `vercel dev` from bundling the contents?

Every time I run a lambda, I have no issues. But when I try to manually bundle it, or run `vercel dev` I get this.

```bash
error: Uncaught AssertionError: Assertion failed.
    at Object.assert ($deno$/util.ts:33:11)
    at compile ($deno$/compiler.ts:1355:5)
    at async tsCompilerOnMessage ($deno$/compiler.ts:1548:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:74:9)
```

So now I am not sure of the issue. If I remove mustache, it works. I had issues with multiple things that I am importing. I am not saying the vanilla code is an issue. I am trying to understand why it's so fragile, and what these libraries are using that can be bundled outside of `now-deno`, but in combination with `now-deno` just fail.

### vercel.dev
```json
{
  "version": 2,
  "functions": {
    "api/**/*.{j,t}s": {
      "runtime": "now-deno@0.4.0",
      "includeFiles": "**/*.html"
    }
  },
  "env": {
    "DENO_UNSTABLE": "true"
  }
}
```

### api/test/index.ts
```ts
import {
  APIGatewayProxyEvent,
  APIGatewayProxyResult,
  Context,
} from "https://deno.land/x/lambda/mod.ts";
import { renderFile } from "https://deno.land/x/mustache/mod.ts";

export async function handler(
  event: APIGatewayProxyEvent,
  context: Context
): Promise<APIGatewayProxyResult> {
  return {
    statusCode: 200,
    body: await renderFile(`template.html`, {
      txt: "HEY",
    }),
    headers: {
      "content-type": "text/html; charset=utf-8",
    },
  };
}
```

### api/test/template.html
```
<p>Hello {{ txt }}</p>
```

**Comment by khrome83** [comment]
Closing this issue, because I feel like Deno was not available in my path. It was not until recently when i tried to install a script that I realized it was missing, even though I had the command.
